# Матрицы и матричные операции
### Часть 1. Матричные операции. Типы матриц
__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

#### Решение

При перемножении количество столбцов левой матрицы, должно совпадать с количеством строк правой матрицы.
На основе этого имеем:

а) $AB$ и $BA$ не определены.

б) $AB$ определено, размерность произведения $2 \times 3$. $BA$ не определено.

в) $AB$ определено, размерность произведения $8 \times 8$. $BA$ тоже определено, размерность произведения $3 \times 3$.

г) $AB$ и $BA$ определены. Размерности в обоих случаях $4 \times 4$.

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

#### Решение

$$A + B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}
$$

$$A \cdot B = 
\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
15 & -3
\end{pmatrix}
$$

$$B \cdot A = 
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}
$$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

#### Решение

$$
3A-2B+4C = 
3
\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}
-2
\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}
+
4
\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}
=
\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}
-
\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}
+
\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}
=
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}
$$

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

#### Решение

$$
AA^{T} = 
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}
=
\begin{pmatrix}
4\cdot4 + 1\cdot 1 & 4\cdot5 - 1\cdot 2 & 4\cdot2 + 1\cdot 3\\ 
5\cdot4 - 2\cdot 1 & 5\cdot5 + 2\cdot 2 & 5\cdot2 - 2\cdot 3\\ 
2\cdot4 + 3\cdot 1 & 2\cdot5 - 3\cdot 2 & 2\cdot2 + 3\cdot 3
\end{pmatrix}
=
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}
$$

$$
A^{T}A = 
\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}
\cdot
\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
=
\begin{pmatrix}
4\cdot4 + 5\cdot 5 + 2 \cdot 2 & 4\cdot1 - 5\cdot 2 + 2 \cdot 3\\ 
1\cdot4 - 2\cdot 5 + 3 \cdot 2 & 1\cdot1 + 2\cdot 2 + 3 \cdot 3
\end{pmatrix}
=
\begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}
$$

In [1]:
import numpy as np

A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'A * A_T =\n{A.dot(A.T)}\n')
print(f'A_T * A =\n{A.T.dot(A)}')

A * A_T =
[[17 18 11]
 [18 29  4]
 [11  4 13]]

A_T * A =
[[45  0]
 [ 0 14]]


__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

#### Решение

In [2]:
def my_dot(A: list, B: list) -> list:
    try:
        # Проверка на равенство длин строк
        for M in (A, B):
            for i in range(1, len(M)):
                if len(M[i]) != len(M[0]):
                    return None

        return [[sum([A[i][k] * B[k][j] for k in range(len(B))]) for j in range(len(B[0]))] for i in range(len(A))]
    
    except (IndexError, TypeError):
        return None

A = [[1, 2], 
     [3 , 4], 
     [5, 6]]

B = [[1, 2, 3, 4], 
     [5, 6, 7, 8]]
    
print(*my_dot(A, B), sep='\n')

[11, 14, 17, 20]
[23, 30, 37, 44]
[35, 46, 57, 68]


#### Проверка

In [3]:
print(np.dot(A, B))

[[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]]


### Часть 2. Определитель. Ранг. Обратная матрица
__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
\sin{x} & -\cos{x}\\ 
\cos{x} & \sin{x}
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$
#### Решение

a)
$
\begin{vmatrix}
\sin{x} & -\cos{x}\\ 
\cos{x} & \sin{x}
\end{vmatrix}
= {\sin{x}}^2 + {\cos{x}}^2 = 1
$

б)
$
\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}
= 4 \cdot 5 \cdot 9 = 180
$

в)
$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=$ $9 \cdot 
\begin{vmatrix}
1 & 2 \\ 
4 & 5 
\end{vmatrix}$ $- 8 \cdot
\begin{vmatrix}
1 & 3\\ 
4 & 6
\end{vmatrix}$ $+ 7 \cdot
\begin{vmatrix}
2 & 3\\ 
5 & 6
\end{vmatrix}$ $= -27 + 48 - 21 = 0$

#### Проверка

In [4]:
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

np.linalg.det(A)

-9.51619735392994e-16

Верно, так как Python считает с погрешностью

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $\det A^{2}$;
    
   б) $\det A^{T}$;
    
   в) $\det (2A) $.
   
#### Решение

а) $\det A^{2} = \det A \cdot \det A = 4 \cdot 4 = 16$

б) $\det A^{T} = \det A = 4$

в) Мы уже знаем, что умножение строки или столбца на $\lambda$ ведет к увеличению $\det$ в $\lambda$ раз. При умножении матрицы на 2, можно представить, что мы умножаем каждую строку или каждый столбец на 2. Пусть строк $n$, тогда:

$\det (2A) = 2^n \det A = 4 \cdot 2^n$, где $n$ - число строк.

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

#### Решение
Добавим удвоенную первую строку ко второй:

$$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix}
=
\begin{vmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{vmatrix}
= 0.
$$

Определитель нулевой, значит матрица вырождена по определению.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

#### Решение

а) Вычтем из третьей строки первую и вторую, получим:

$$
rk\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}
=
rk\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
0 & 0 & 0
\end{pmatrix}
=
rk\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix}
=
rk\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2
\end{pmatrix}
= 2,$$

#### Проверка

In [5]:
A = np.array([[1, 2, 3], 
              [1, 1, 1], 
              [2, 3, 4]])

np.linalg.matrix_rank(A)

2

б) Вычтем из третьей строки первую и вторую, получим:

$$
rk \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}
=
rk \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}
=
rk \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\
2 & 3 & 5 & 6
\end{pmatrix}
=
rk \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 1 & 1\\
2 & 3 & 5 & 6
\end{pmatrix}
=3
$$

#### Проверка

In [6]:
A = np.array([[0, 0, 2, 1], 
              [0, 0, 2, 2], 
              [0, 0, 4, 3], 
              [2, 3, 5, 6]])

np.linalg.matrix_rank(A)

3