In [1]:
import numpy as np
import scipy.linalg

#### __1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

In [2]:
# а)

A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')

A:
[[ 1 -2]
 [ 3 -4]]

b:
[1 7]

det(A): 2.0000000000000004

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[ 1 -2]
 [ 7 -4]]

det(A1): 9.999999999999998

A2:
[[1 1]
 [3 7]]

det(A2): 4.0

x1 = 4.999999999999998
x2 = 1.9999999999999996


In [3]:
# б)

A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1:]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b, A[:, 2]])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

A3 = np.column_stack([A[:, 0:2], b])
det_A3 = np.linalg.det(A3)

print(f'A3:\n{A3}\n')
print(f'det(A3): {det_A3}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')
print(f'x3 = {det_A3 / det_A}')

A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b:
[10 -2  1]

det(A): 42.99999999999998

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

det(A1): 86.00000000000004

A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

det(A2): -43.000000000000014

A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

det(A3): 42.99999999999998

x1 = 2.0000000000000018
x2 = -1.0000000000000009
x3 = 1.0


#### __2.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

а)<br>

Матрица коэффициентов:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$

Умножим 1 строку на 2 и вычтем из 2 строки:<br>

Матрица U:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
3 & 26 & 30
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
I_{31} & I_{32} & 1
\end{pmatrix}$

Умножим 1 строку на 3 и вычтем из 3 строки:<br>

Матрица U:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & I_{32} & 1
\end{pmatrix}$

Умножим 2 строку на 4 и вычтем из 3 строки:<br>

Матрица U:<br>

$\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

In [4]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])
U = np.array([[1, 2, 4], [0, 5, 4], [0, 0, 2]])
L = np.array([[1, 0, 0], [2, 1, 0], [3, 4, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]

U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]

LU:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]



б) <br>

Матрица коэффициентов:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
2 & 5 & 8 & 9 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Умножим 1 строку на 2 и вычтем из 2 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
3 & 18 & 29 & 18 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
I_{31} & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 1 строку на 3 и вычтем из 3 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
4 & 22 & 53 & 33
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
I_{41} & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 1 строку на 4 и вычтем из 4 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 15 & 23 & 6 \\
0 & 18 & 45 & 17
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & I_{32} & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 2 строку на 5 и вычтем из 3 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 18 & 45 & 17
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & I_{42} & I_{43} & 1
\end{pmatrix}$

Умножим 2 строку на 6 и вычтем из 4 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 21 & 11
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & I_{43} & 1
\end{pmatrix}$

Умножим 3 строку на 7 и вычтем из 4 строки: <br>

Матрица U:<br>

$\begin{pmatrix}
1 & 1 & 2 & 4 \\ 
0 & 3 & 4 & 1 \\ 
0 & 0 & 3 & 1 \\
0 & 0 & 0 & 4
\end{pmatrix}$

Матрица L:<br>

$\begin{pmatrix}
1 & 0 & 0 & 0 \\ 
2 & 1 & 0 & 0 \\ 
3 & 5 & 1 & 0 \\
4 & 6 & 7 & 1
\end{pmatrix}$

In [5]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
U = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0, 0, 0, 4]])
L = np.array([[1, 0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])

LU = np.dot(L, U)

print(f'A:\n{A}\n')
print(f'L:\n{L}\n')
print(f'U:\n{U}\n')
print(f'LU:\n{LU}\n')

A:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]

L:
[[1 0 0 0]
 [2 1 0 0]
 [3 5 1 0]
 [4 6 7 1]]

U:
[[1 1 2 4]
 [0 3 4 1]
 [0 0 3 1]
 [0 0 0 4]]

LU:
[[ 1  1  2  4]
 [ 2  5  8  9]
 [ 3 18 29 18]
 [ 4 22 53 33]]



#### __3.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

In [6]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

print(f'lu:\n{lu}\n')
print(f'piv:\n{piv}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.00000000e+00  2.44249065e-16  1.00000000e+00]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]

lu:
[[11.          7.          5.        ]
 [ 0.81818182  2.27272727 -0.09090909]
 [ 0.18181818 -0.12        2.08      ]]

piv:
[1 2 2]



#### __4.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

In [7]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

K = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(K, b)

print(f'A:\n{A}\n')
print(f'K:\n{K}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

K:
(array([[  9.,  -5.,   5.],
       [-45.,   5.,   2.],
       [ 45., -15.,   3.]]), False)

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]



#### __5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [8]:
def LU(A): 
  
    n = len(A)
    
    L = [[0 for _ in range(n)] for _ in range(n)]
    U = [[0 for _ in range(n)] for _ in range(n)] 
                  
    for i in range(n): 

        for k in range(i, n):  

            s = 0; 
            for j in range(i): 
                
                s += (L[i][j] * U[j][k]) 
  
            U[i][k] = A[i][k] - s
  
        for k in range(i, n): 
        
            if (i == k):
                
                L[i][i] = 1
                
            else:
                
                s = 0
                
                for j in range(i): 
                    
                    s += (L[k][j] * U[j][i])
  
                L[k][i] = int((A[k][i] - s) / U[i][i]) 
  
    return L, U


In [9]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

L, U = LU(A)

print(f'A:\n{A}\n')
print(f'L:\n{np.array(L)}\n')
print(f'U:\n{np.array(U)}\n')
print(f'LU:\n{np.array(L) @ np.array(U)}\n')

A:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

L:
[[1 0 0]
 [2 1 0]
 [3 4 1]]

U:
[[1 2 4]
 [0 5 4]
 [0 0 2]]

LU:
[[ 1  2  4]
 [ 2  9 12]
 [ 3 26 30]]

