# Линейные преобразования
### Собственные векторы и собственные значения операторов
__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\left(\begin{array}{cc}
{-1} & {-6}\\ 
{2} & {6}
\end{array}\right)$$

#### Решение

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$\left|\begin{array}{cc}
{-1-\lambda} & {-6}\\ 
{2} & {6-\lambda}
\end{array}\right| = 0$

$(-1 -\lambda)(6 - \lambda) - (-12) = 0$

$\lambda^2 - 5\lambda + 6 = 0$

$\lambda_1 = 3, \:\: \lambda_2 = 2$

1) $\lambda_1 = 3$

$\left(\begin{array}{cc}
{-1 - 3}& {-6}\\ 
{2} & {6 -3}
\end{array}\right)$ $\left(\begin{array}{c}
{x_{1}}\\ 
{x_{2}}
\end{array}\right)=0$

$\left(\begin{array}{cc}
{-4}& {-6}\\ 
{2} & {3}
\end{array}\right)$ $\left(\begin{array}{c}
{x_{1}}\\ 
{x_{2}}
\end{array}\right)=0$

$2 x_1 + 3 x_2 = 0$

Собственный вектор, например, (3, -2)

2) $\lambda_1 = 2$

$\left(\begin{array}{cc}
{-1 - 2} & {-6}\\ 
{2} & {6 -2}
\end{array}\right)$ $\left(\begin{array}{c}
x_{1}\\ 
x_{2}
\end{array}\right)=0$

$\left(\begin{array}{cc}
{-3} & {-6}\\ 
{2} & {4}
\end{array}\right)$ $\left(\begin{array}{c}
x_{1}\\ 
x_{2}
\end{array}\right)=0$

$x_1 + 2 x_2 = 0$

Собственный вектор, например, (1, -2)

#### Проверка

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

a = np.array([[-1, -6], 
              [ 2,  6]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]

Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]


#### Ответ
$\lambda_1 = 3, \:\: (3, -2)$ — соответствующий собственный вектор,

$\lambda_2 = 2, \:\: (1, -2)$ — соответствующий собственный вектор.

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\left(\begin{array}{cc}
{-1} & {0}\\ 
{0} & {-1}
\end{array}\right).$$

Показать, что __любой__ вектор является для него собственным.

#### Решение

_Собственный вектор_ оператора $\textbf{A}$ — это такой ненулевой вектор, действие оператора на который сводится к умножению его на число:

$$\textbf{A}x=\lambda x.$$

Это действительно так:

$\forall (x_1, x_2): \left(\begin{array}{cc}{-1} & {0}\\ {0} & {-1}\end{array}\right)$ $\left(\begin{array}{c}{x_1}\\{x_2}\end{array}\right) = $ $-1 \left(\begin{array}{c}{x_1}\\{x_2}\end{array}\right)$.

Собственное значение $-1$.

__3.__ Пусть линейный оператор задан матрицей

$$A=\left(\begin{array}{cc}
{1} & {1}\\ 
{-1} & {3}
\end{array}\right).$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

#### Решение

Попробуем решить уравнение относительно $\lambda$:

$\textbf{A}x=\lambda x.$

$\left(\begin{array}{cc}
{1} & {1}\\ 
{-1} & {3}
\end{array}\right)$ $\left(\begin{array}{c}{1}\\{1}\end{array}\right) = $ $\lambda \left(\begin{array}{c}{1}\\{1}\end{array}\right)$

$\left\{\begin{array}{l}
{1+1=\lambda} \\
{-1+3=\lambda}
\end{array}\right.$

$\left\{\begin{array}{l}
{\lambda = 2} \\
{\lambda = 2}
\end{array}\right.$

Вектор $(1, 1)$ является собственным для матрицы $\textbf{A}$. Собственное значение $2$.

#### Проверка

In [2]:
a = np.array([[ 1, 1], 
              [-1, 3]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]

Собственные значения:
[2. 2.]

Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


__4.__ Пусть линейный оператор задан матрицей

$$A=\left(\begin{array}{ccc}
{0} & {3} & {0}\\ 
{3} & {0} & {0}\\
{0} & {0} & {3}
\end{array}\right)$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

#### Решение

$\textbf{A}x=\lambda x$

$(\textbf{A} - \lambda)x=0$

$\left(\begin{array}{ccc}
{-\lambda} & {3} & {0}\\ 
{3} & {-\lambda} & {0}\\
{0} & {0} & {3-\lambda}
\end{array}\right)$ $\left(\begin{array}{c}{3}\\{-3}\\{-4}\end{array}\right) = 0$

$\left\{\begin{array}{l}
{- 3\lambda - 9 = 0} \\
{9 + 3\lambda = 0} \\
{-12 + 4\lambda = 0}
\end{array}\right.$

$\left\{\begin{array}{l}
{\lambda = -3} \\
{\lambda = -3} \\
{\lambda = 3}
\end{array}\right.$

Система несовместна, значит вектор $x=(3, -3, -4)$ не является собственным вектором линейного оператора $\textbf{A}$.

#### Проверка

In [3]:
a = np.array([[0, 3, 0], 
              [3, 0, 0], 
              [0, 0, 3]])

w, v = np.linalg.eig(a)

print(f'Матрица A:\n{a}\n')
print(f'Собственные значения:\n{w}\n')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]

Собственные значения:
[ 3. -3.  3.]

Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]


Все верно. $x=(3, -3, -4)$ не является собственным