# Урок 2

## Дискретные случайные величины. Закон распределения вероятностей.  Биномиальный закон распределения. Распределение Пуассона

### Случайные величины

__Случайная величина__ — величина, которая в результате опыта принимает некоторое значение, неизвестное заранее.

__Дискретные__ случайные величины принимают конечное или счётное множество значений (например, _натуральные_ или _рациональные_ числа). __Непрерывные__ случайные величины принимают несчётное множество значений (например, _вещественные_ числа). 

Примеры дискретных случайных величин:

1. Сумма очков при $100$-кратном подбрасывании игрального кубика.
2. Число метеоритов, упавших на Землю за год.
3. Количество машин, которые успевают проехать через данный светофор за один цикл.

__Пример 1__

Смоделируем стократное подбрасывание монетки. Рассмотрим случайную величину, равную числу выпаданий орла.

In [1]:
import numpy as np

In [21]:
np.random.binomial(n=100, p=0.5)

49

Можно повторить этот эксперимент большее количество раз (например, $50$ раз) и посмотреть, какие получаются значения.

In [23]:
print(np.random.binomial(n=100, p=0.5, size=50))

[52 52 51 43 53 47 63 53 49 52 50 47 43 57 47 56 42 47 51 55 40 42 47 44
 57 48 44 52 49 58 47 52 53 57 49 47 56 41 45 47 39 45 50 42 55 54 52 45
 41 53]


Пусть $X$ — дискретная случайная величина. __Закон распределения__ этой случайной величины — это соответствие между значениями, которые принимает эта величина, и вероятностями, с которыми она их принимает.

__Пример 2__

Пусть $X$ — сумма значений двух подбрасываемых игральных кубиков. Вот её закон распределения:

<table border="3">
    <tr>
        <th>$x$</th>
        <td>2</td>
        <td>3</td>
        <td>4</td>
        <td>5</td>
        <td>6</td>
        <td>7</td>
        <td>8</td>
        <td>9</td>
        <td>10</td>
        <td>11</td>
        <td>12</td>
</tr>
    <tr>
        <th>$P(X=x)$</th>
        <td>0.028</td>
        <td>0.056</td>
        <td>0.083</td>
        <td>0.111</td>
        <td>0.139</td>
        <td>0.167</td>
        <td>0.139</td>
        <td>0.111</td>
        <td>0.083</td>
        <td>0.056</td>
        <td>0.028</td>
    </tr>
</table>

__Пример 3__

В урне $8$ шаров, из которых $5$ белых, остальные — чёрные. Наудачу вынимают $3$ шара. Найти закон распределения количества белых шаров в выборке.

Принимаемые значения данной случайной величины будут: $x_1 = 0$, $x_2 = 1$, $x_3 = 2$, $x_4 = 3$.

Посчитаем вероятность того, что $X = 0$, т.е. что среди трёх вытянутых шаров нет ни одного белого. Значит, вытянуты в точности все чёрные шары. Такое возможно лишь в одном случае.

Кстати, из скольки? Общее число способов вытянуть $3$ шара из урны с $8$ шарами — число сочетаний:
$$C_8^3 = \dfrac{8!}{3! \cdot 5!} = \dfrac{8 \cdot 7 \cdot 6}{6} = 56.$$

Итак, $P(X = 0) = \dfrac{1}{56}$.

Событие $X = 1$ означает, что среди вытянутых шаров один белый и два чёрных: $P(X = 1) = \dfrac{C_5^1 \cdot C_3^2}{56} = \dfrac{15}{56}$. Аналогично,
$$P(X = 2) = \dfrac{C_5^2 \cdot C_3^1}{56} = \dfrac{30}{56}, \:\:
P(X = 3) = \dfrac{C_5^3}{56} = \dfrac{10}{56}.$$

Заметим, что сумма этих четырёх вероятностей равна $1$.

Пусть $X$, $Y$ — дискретные случайные величины, причём $X$ принимает значения $x_j$ с вероятностями $P(X = x_j)$, $j = 1,2,\dots$, а $Y$ принимает значения $y_k$ с вероятностями $P(Y = y_k)$, $k = 1,2,\dots$.

* Их __сумма__ $Z = X + Y$ — случайная величина, которая принимает значения $z_{jk} = x_j + y_k$ с вероятностями $P(X = x_j, Y = y_k)$.
* Аналогично считаются __разность__ и __произведение__ случайных величин, надо лишь заменить соответствующие символы операций.
* __Квадрат__ $Z = X^2$ — случайная величина, которая принимает значения $z_j = x_j^2$ по тому же закону распределения, что и $X$.

__Пример 4__

Разберёмся, почему квадрат случайной величины считается именно так. 

По определению произведения случайных величин, квадрат величины $X$ должен принимать все возможные значения $x_j x_k$ с вероятностями $P(X = x_j, X = x_k)$.

Но случайная величина не может принимать несколько значений одновременно. Отсюда следует, что если $j \neq k$, то $P(X = x_j, X = x_k) = 0$.

Поэтому остаются значения $x_j^2$ с вероятностями $P(X = x_j, X = x_j) = P(X = x_j)$.

__Математическим ожиданием__ случайной величины $X$ называется среднее значение величины $X$ при стремлении количества испытаний к бесконечности. Обозначается $M(X)$.

Если $X$ — дискретная случайная величина, принимающая значения $x_j$ с вероятностями $p_j = P(X = x_j)$, 
$j = 1,2, \dots$, то
$$M(X) = \displaystyle\sum_j p_j x_j = p_1 x_1 + p_2 x_2 + \dots$$

__Пример 5__

Посчитаем математическое ожидание случайной величины из примера 2.

In [24]:
x_values = np.arange(2, 13)

print(x_values)

[ 2  3  4  5  6  7  8  9 10 11 12]


In [25]:
x_probabilities = np.array([1, 2, 3, 4, 5, 6, 5, 4, 3, 2, 1]) / 36

print(x_probabilities)

[0.02777778 0.05555556 0.08333333 0.11111111 0.13888889 0.16666667
 0.13888889 0.11111111 0.08333333 0.05555556 0.02777778]


Чтобы посчитать математическое ожидание, нужно поэлементно перемножить значения этих двух массивов (первый с первым, второй со вторым и т.д.), затем сложить результаты. С помощью библиотеки `numpy` это можно сделать так:

In [26]:
m = x_values.dot(x_probabilities)

print(m)

6.999999999999999


Подробнее про умножение матриц [здесь](https://ru.wikipedia.org/wiki/%D0%A3%D0%BC%D0%BD%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BC%D0%B0%D1%82%D1%80%D0%B8%D1%86) и [здесь](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html).

__Дисперсией__ случайной величины $X$ называется математическое ожидание квадрата отклонения случайной величины от её математического ожидания:
$$D(X) = M \left( (X - M(X))^2 \right).$$

Дисперсия является мерой разброса случайной величины относительно её среднего значения. 

__Пример 6__

Посчитаем дисперсию случайной величины из примера 2. Её математическое ожидание мы уже считали, оно равно:

In [28]:
m = 7
m

7

Далее, определим случайную величину $Y = X - M(X)$. Она будет принимать значения:

In [29]:
y_values = x_values - m

print(y_values)

[-5 -4 -3 -2 -1  0  1  2  3  4  5]


Отметим, что распределения вероятностей у величины $Y$ такое же, что и у $X$.

Далее, возведём эту величину в квадрат, тем самым получим новую случайную величину $Z$ со всё еще таким же распределением вероятностей:

In [30]:
z_values = y_values ** 2

print(z_values)

[25 16  9  4  1  0  1  4  9 16 25]


Итак, дисперсия случайной величины $X$ равна:

In [31]:
d = z_values.dot(x_probabilities)

print(d)

5.833333333333334


### Законы распределения случайных величин

Пусть имеется некоторое событие $A$, которое наступает с вероятностью $p$. __Биномиальный закон__ описывает распределение случайной величины $X$, задающей число наступлений события $A$ в ходе проведения $n$ независимых опытов.

Биномиальный закон распределения описывается __формулой Бернулли__:
$$P(X = k) = C_n^k p^k (1 - p)^{n - k}$$

__Пример 7__

Доказать формулу Бернулли довольно легко, используя уже известные нам правила комбинаторики. То, что событие $A$ в результате проведения $n$ независимых опытов наступило $k$ раз означает, что $n - k$ раз наступило событие $\overline{A}$. Вероятность наступления такого события равна $1 - p$. 

При этом наступить событие $A$ могло в любые $k$ «моментов» из $n$, поэтому число вариантов таких «моментов» равно $C_n^k$. Наконец, эксперименты проводились независимо, поэтому итоговая вероятность равна $C_n^k p^k (1 - p)^{n - k}$.

Математическое ожидание и дисперсию для биномиально распределённой дискретной величины можно вычислить по формулам:
$$M(X) = np, \: D(X) = np(1 - p).$$

__Пример 8__

Посчитаем распределение числа выпаданий орла при трёхкратном подбрасывании монеты. Возможные значения такой случайной величины: $x_1 = 0$, $x_2 = 1$, $x_3 = 2$, $x_4 = 3$.

Посчитаем вероятность каждого значения:
$$P(X = 0) = C_n^k p^k (1 - p)^{n - k} = C_3^0 \cdot 0.5^0 \cdot 0.5^3 = \frac{3!}{0! \: (3-0)!} \cdot 0.5^0 \cdot 0.5^3 = 1 \cdot 1 \cdot 0.125 = 0.125.$$
$$P(X = 1) = C_3^1 \cdot 0.5^1 \cdot 0.5^2 = \frac{3!}{1! \: 2!} \cdot 0.5^1 \cdot 0.5^2 = 3 \cdot 0.5 \cdot 0.25 = 0.375.$$
$$P(X = 2) = C_3^2 \cdot 0.5^2 \cdot 0.5^1 = \frac{3!}{2! \: 1!} \cdot 0.5^2 \cdot 0.5^1 = 0.375.$$
$$P(X = 3) = C_3^3 \cdot 0.5^3 \cdot 0.5^0 = \frac{3!}{3! \: 0!} \cdot 0.5^3 \cdot 0.5^0 = 0.125.$$

Итак, закон распределения такой случайной величины:

<table border="3">
    <tr>
        <th>$x$</th>
        <td>0</td>
        <td>1</td>
        <td>2</td>
        <td>3</td>
    </tr>
    <tr>
        <th>$P(X = x)$</th>
        <td>0.125</td>
        <td>0.375</td>
        <td>0.375</td>
        <td>0.125</td>
    </tr>
</table>

__Пример 9__

Посчитаем математическое ожидание распределения из предыдущего примера. Поскольку $n = 3$ и $p = 0.5$, получаем:
$$M(X) = 3 \cdot 0.5 = 1.5.$$

Результат можно понимать так: в среднем при трёхкратном подбрасывании монеты орёл выпадает $1.5$ раза.

Дисперсия такой величины:
$$D(X) = 3 \cdot 0.5 \cdot (1 - 0.5) = 0.75.$$

__Распределение Пуассона__

Дискретная случайная величина $X$ имеет __распределение Пуассона__, если её возможные значения — числа $0$, $1$, $2$, $\dots$ (счётное множество значений), а соответствующие вероятности выражаются формулой Пуассона:
$$P(X = k) = \dfrac{a^k e ^{-a}}{k!}.$$

Здесь $a$ — положительное вещественное число.

Распределение Пуассона хорошо описывает счетчики событий. Например, распределение Пуассона описывает:
* число опечаток в большом тексте,
* число бракованных деталей в большой партии,
* число автобусов, проехавших за определенное время мимо автобусной остановки.

Параметр $a$ здесь отвечает за интенсивность рассматриваемых событий.

Математическое ожидание и дисперсия распределения Пуассона равны:
$$M(X) = D(X) = a.$$

Распределение Пуассона является предельным случаем биномиального. Если в последнем имеется очень большое число экспериментов ($n \rightarrow \infty$), а вероятность наступления события $A$ достаточно мала (можно считать, что $p \approx a/n$), то такое распределение становится очень похоже на распределение Пуассона с параметром $a = np$.

__Пример 10__

Вероятность того, что письмо, поступающее на определённый почтовый ящик, окажется спамом, составляет $0.01$. Какова вероятность того, что в течение месяца на почтовый ящик придёт $11$ писем со спамом, если в данный месяц на почту пришло всего $1000$ писем?

Поскольку мы имеем дело со счётчиком (число писем со спамом в месяц), мы можем допустить, что рассматриваемая случайная величина имеет распределение Пуассона. Чтобы найти её параметр $a$, вспомним, что чем выше число экспериментов, тем больше биномиальное распределение «похоже» на распределение Пуассона с параметром $a = np$. В нашем случае $a = 1000 \cdot 0.01 = 10$. Итак,
$$P(X = 11) = \dfrac{10^{11} \cdot e^{-10}}{11!} \approx 0.1137.$$

In [32]:
a = 10
k = 11

(a ** k) * (np.exp(-a)) / np.math.factorial(k)

0.11373639611012118

__Другие дискретные распределения__

* __Дискретное равномерное__: случайная величина $X$ принимает $n$ различных значений с одинаковой вероятностью $1 / n$. Не путать с _непрерывным равномерным_.
* __Геометрическое__: число независимых испытаний до первого наступления события $A$, где событие $A$ наступает в однократном испытании с вероятностью $p$. В этом случае
$$P(X = k) = (1 - p)^k \cdot p$$

### Упражнения

__Задача 1__

Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите `M(X)`, `D(X)`.

__Задача 2__

Вероятность попадания в цель при одном выстреле равна 0.01. Какова вероятность того, что число попаданий при 200 выстрелах будет не менее 5 и не более 10?

__Задача 3__

В условиях предыдущей задачи сколько выстрелов нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 10 раз будет совершено попадание?

_Подсказка_. Как посчитать `P(X >= k)` для величины `X`, имеющей распределение Пуассона? Здесь предстоит немножко покодить.
